import type { Metadata } from "next";
import "./globals.css";
import React, {ReactNode} from "react";
import {Navigation} from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <header>
        <Navigation />
      </header>
        {children}
      </body>
    </html>
  );
}
